// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzqlghoefcmuevtkvxum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6cWxnaG9lZmNtdWV2dGt2eHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MTg2NzcsImV4cCI6MjA3MjA5NDY3N30.0PPrF8sKk5ZvscOH0WdTkddwEu7wRIXbCZaxVly7tYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});